name: afs_fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - fastapi
  - uvicorn
  - pytest
  - pytest-bdd
  - pytest-mock
  - pydantic
  - rich
  - factory_boy
  - Faker
  - black
  - flake8
  - isort
  - pip
