name: Docs Sync

on:
  push:
    branches: [ "main" ]
    paths:
      - 'README.md'
      - 'docs/convert_readme_to_index_html.py'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install converter deps
        run: |
          python -m pip install --upgrade pip
          pip install markdown
      - name: Convert README.md to docs/index.html
        run: |
          python docs/convert_readme_to_index_html.py --in README.md --out docs/index.html
      - name: Commit and push updated docs
        run: |
          if [[ -n "$(git status --porcelain docs/index.html)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/index.html
            git commit -m "docs: sync docs/index.html from README.md"
            git push
          else
            echo "No doc changes to commit."
          fi
